### ISSUE TITLE
Backend Travis build

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/sciadro-backend#10]
Travis must be connected to this repository to provide a continuous integration of the involved components (build and unit tests run). Travis also supports [Dockers in builds](https://docs.travis-ci.com/user/docker/) so we can leverage on this features that is interesting for us.

**Comment by sergey-misuk-yotec** [comment]
Where are you going to store Docker images?

**Comment by tdipisa** [comment]
@sergey-misuk-yotec I think tha we could use this approach: [building-a-docker-image-from-a-dockerfile](https://docs.travis-ci.com/user/docker/#building-a-docker-image-from-a-dockerfile)
