### ISSUE TITLE
Remove frames, telemetry_att and telemetry_pos array from Mission

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/sciadro-backend#29]
Remove frames[...], telemetry_att[...] and telemetry_pos[...] array from [Mission REST output](http://164.132.80.75:8081/assets/74f76dd5-c9e4-47c6-b6c2-d54796407cba/missions/d6cf148c-8da1-4843-a5d8-f809078af45b/) because they aren't needed.

**Comment by MV88** [comment]
they should be removed also here [/assets/74f76dd5-c9e4-47c6-b6c2-d54796407cba/missions/](http://164.132.80.75:8081/assets/74f76dd5-c9e4-47c6-b6c2-d54796407cba/missions/)
