### ISSUE TITLE
Asset geometry is currently missing

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/sciadro-backend#35]
At the moment we don't have geometries stored in DB for Assets. Even if Asset's geometry is not mandatory, for test purposes we need **some** assets (not all of them) with a geometry (this geometry can be at this stage something similar to the one calculated from the telemetry).

**Comment by petrus7** [comment]
Current implementation will consume geometry like this
body: 
{.
.
.
geometry :  [
            [
                10.4374221,
                43.6524748
            ],
            [
                10.4374223,
                43.6524749
            ],
            [
                10.4374222,
                43.6524752
            ],
            [
                10.4374222,
                43.6524753
            ],
]
.
.
.
}
