### ISSUE TITLE
increase test coverage

### ISSUE THREAD

**Issue by petrus7** [geosolutions-it/sciadro-backend#58]
Write integration tests for crud operations

Include codecov io into travis build

**Comment by tdipisa** [comment]
Some useful docs here about including codecov in travis build with docker:

[Testing with Docker](https://docs.codecov.io/docs/testing-with-docker)
[Sandbox for setting up docker for CI and codecov with Python](https://github.com/marshallmcdonnell/example-docker-codecov-ci)
